import Head from "next/head";
import Image from "next/image";
import style from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${style.container} container`}>
        <div className="row d-flex gy-2">
          <div className="col-md-12">
            <h1 className={style.app_name1}>
              &lt;Hunting <span className={style.app_name2}>Coder/&gt;</span>
            </h1>
          </div>
          <div className="col-md-12 d-flex flex-wrap justify-content-center btn_container">
            <span className={style.btn_code}>#JavaScript</span>
            <span className={style.btn_code}>#React</span>
            <span className={style.btn_code}>#NextJS</span>
            <span className={style.btn_code}>#WebDev</span>
            <span className={style.btn_code}>#Algorithms</span>
            <span className={style.btn_code}>#DataStructures</span>
          </div>
          <div className="col-md-12"></div>
          <div className={style.home_text} style={{width: "90vw"}}>
            Hunting Coder is a blog about programming languages. It covers
            tutorials, tips, and insights to help you learn and explore
            different languages and improve your coding skills.Discover the
            latest in coding and development. From algorithms to frameworks,
            your daily dose of programming insights.
          </div>
          <div />
        </div>
      </div>
    </>
  );
}
